version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.2
  - dependency-name: husky
    versions:
    - 5.1.0
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: typedoc
    versions:
    - 0.20.23
